-- Oracle DB 초기화 스크립트
-- HanaChain 프로젝트용 기본 스키마 및 테이블 생성

-- 사용자 테이블스페이스 생성 (옵션)
-- CREATE TABLESPACE hanachain_tbs 
-- DATAFILE 'hanachain_tbs.dbf' 
-- SIZE 100M 
-- AUTOEXTEND ON 
-- NEXT 10M;

-- 예제 테이블 생성
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    transaction_type VARCHAR2(20) NOT NULL,
    amount NUMBER(19, 4) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_transaction 
        FOREIGN KEY (user_id) 
        REFERENCES users(user_id)
);

-- 인덱스 생성
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_transactions_user ON transactions(user_id);
CREATE INDEX idx_transactions_status ON transactions(status);

-- 시퀀스 생성 (필요시)
-- CREATE SEQUENCE seq_user_id START WITH 1 INCREMENT BY 1;
-- CREATE SEQUENCE seq_transaction_id START WITH 1 INCREMENT BY 1;

-- 권한 부여 (APP_USER에게)
-- GRANT ALL PRIVILEGES ON users TO APP_USER;
-- GRANT ALL PRIVILEGES ON transactions TO APP_USER;

COMMIT;
